name: arcsql

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - name: create dacpac
        run: & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe' kcdemodbproject.sqlproj /p:Configuration=Release
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
         - name: Azure SQL Deploy
        - uses: azure/sql-action@v1
          with:
            server-name: arcdatabasedevops.database.windows.net
            connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
            dacpac-package: './Database2.dacpac'

        # Azure logout 
        - name: logout
          run: |
             az logout
